### ISSUE TITLE
Some suggestions for collaboration

### ISSUE THREAD

**Issue by wuyilingwei** [Agroqirax/TimberbornNederlandsTaalpakket#1]
I wrote a fully automatic python file for Chinese translation. I think we can cooperate. We just need to modify some of its logic and change the language of AI prompt words.

Here is my project:
https://github.com/wuyilingwei/Timberborn_Mods_Universal_zhCN_Translate

**Comment by Agroqirax** [comment]
Looks like a cool project, but I think better accuracy is possible with a dedicated translation library like [deep-translator](https://pypi.org/project/deep-translator/).
I might contribute a bit in the future, but at the moment I'm busy enough with other projects.

**Comment by wuyilingwei** [comment]
You are right, but in fact, after my test, chatgpt's translation is more accurate than deepl, and cheaper.
This is just using the o1-mini model. By compressing the prompt words, it only costs $1 to translate about half million words. It might do better if it followed the standard prompt words.
